name: Build Battlegrounds Plugin

on:
  push:
    paths:
      - '**.java'
      - 'plugin.yml'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download dependencies
        run: |
          mkdir -p lib
          wget -O lib/paper-api.jar https://repo.papermc.io/repository/maven-snapshots/io/papermc/paper/paper-api/1.21.5-R0.1-SNAPSHOT/paper-api-1.21.5-R0.1-20250618.110345-23.jar
          wget -O lib/adventure-platform-bukkit.jar https://repo1.maven.org/maven2/net/kyori/adventure-platform-bukkit/4.3.1/adventure-platform-bukkit-4.3.1.jar
          wget -O lib/adventure-text-serializer-legacy.jar https://repo1.maven.org/maven2/net/kyori/adventure-text-serializer-legacy/4.13.1/adventure-text-serializer-legacy-4.13.1.jar
          wget -O lib/jetbrains-annotations.jar https://repo1.maven.org/maven2/org/jetbrains/annotations/24.1.0/annotations-24.1.0.jar
          wget -O lib/guava.jar https://repo1.maven.org/maven2/com/google/guava/guava/33.2.0-jre/guava-33.2.0-jre.jar
          wget -O lib/adventure-api.jar https://repo1.maven.org/maven2/net/kyori/adventure-api/4.14.0/adventure-api-4.14.0.jar
          wget -O lib/examination-api.jar https://repo1.maven.org/maven2/net/kyori/examination-api/1.3.0/examination-api-1.3.0.jar
          wget -O lib/bungeecord-chat.jar https://repo1.maven.org/maven2/net/md-5/bungeecord-chat/1.21-R0.1/bungeecord-chat-1.21-R0.1.jar
          wget -O lib/adventure-key.jar https://repo1.maven.org/maven2/net/kyori/adventure-key/4.23.0/adventure-key-4.23.0.jar

      - name: Compile plugin
        run: |
          mkdir -p build
          javac -cp "lib/*" -d build src/io/codejava/mc/pubg/Battlegrounds.java

      - name: Package plugin jar
        run: |
          mkdir -p jar
          cp plugin.yml build/
          cd build
          jar cf ../jar/Battlegrounds.jar plugin.yml io
          cd ..

      - name: Upload plugin jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: Battlegrounds
          path: jar/Battlegrounds.jar


