name: Build Battlegrounds Plugin

on:
  push:
    paths:
      - '**.java'
      - 'plugin.yml'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download PaperMC API
        run: |
          mkdir -p lib
          curl -L -o lib/paper-api.jar https://repo.papermc.io/repository/maven-public/io/papermc/paper/paper-api/1.20.6-R0.1-SNAPSHOT/paper-api-1.20.6-R0.1-20240531.093857-1.jar
          file lib/paper-api.jar | grep 'Zip archive data' || (echo "Download failed or not a jar"; exit 1)

      - name: Compile plugin
        run: |
          mkdir -p build
          javac -cp lib/paper-api.jar -d build src/io/codejava/mc/pubg/Battlegrounds.java

      - name: Package plugin jar
        run: |
          mkdir -p jar
          cp plugin.yml build/
          cd build
          jar cf ../jar/Battlegrounds.jar .
          cd ..

      - name: Upload plugin jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: Battlegrounds
          path: jar/Battlegrounds.jar


